---
- astyle
- autopep8
- black
- brittany
- clang-format
- dfmt
- elm-format
- google-java-format
- hindent
- hlint
- jdt
#- jq
- ormolu
- pg_format
- php-cs-fixer
- prettier
- prettier-markdown
#- prettier-ruby
- prettier-yaml
- reorder-python-imports
- rubocop
- rustfmt
- shellharden
- shfmt
- stylish-haskell
- terraform
- yapf
